  - name: Java | Add apt repository
    apt_repository: repo='ppa:openjdk-r/ppa'
    become: yes
    tags:
        -java


  - name: Java | Install
    apt: update-cache=yes force=yes state=present pkg=openjdk-{{java_version}}-jdk
    become: yes
    tags:
        -java
